// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package api

import (
	"github.com/fajarsep12dev/go-api/api/auth"
	"github.com/jinzhu/gorm"
)

import (
	_ "github.com/fajarsep12dev/go-api/docs"
)

// Injectors from wire.go:

func initAuthService(db *gorm.DB) auth.AuthService {
	authRepository := auth.ProvideAuthRepository(db)
	authService := auth.ProvideAuthService(authRepository)
	return authService
}
